name: Build transGUI exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install lazarus
      run: |
        choco install lazarus -y --force

    - name: Find and add lazbuild to PATH
      run: |
        $lazbuildPath = Get-ChildItem -Recurse -Filter "lazbuild.exe" -Path "C:\ProgramData\chocolatey\lib\lazarus" 2>$null | Select-Object -First 1 -ExpandProperty DirectoryName
        if ($lazbuildPath) {
          echo "$lazbuildPath" >> $env:GITHUB_PATH
        } else {
          echo "lazbuild.exe not found"
          exit 1
        }

    - name: Compile transGUI
      run: |
        lazbuild main.pas

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: transgui-binary
        path: ./transgui.exe
